// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(74,50,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(7,188,2^(36.055879))
// 
// Ring
// degree d = 64
// modulus q = 332306998946228968225951765070087957, log(q) ~ 118.0
// factors q = q1
// 
// Compression
// D = 13
// gamma = 3587354, log(gamma) ~ 21.774489
// 
// Dimensions of secrets
// s1: m1 = 64
// m: l = 32
// s2: m2 = 124
// 
// Size of secrets
// l2(s1) <= alpha = 204.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 32)
// exact euclidean: yes (dimensions: [32, 32], bounds: [198.4, 8.796093e+11])
// approximate infinity: yes (psi: 2797.9254, dimension: 64, bound: 2.7021598e+15)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 406323.2, log(stdev1/1.55) = 18.0
// stdev2 = 12697.6, log(stdev2/1.55) = 13.0
// stdev3 = 54535776737689.6, log(stdev3/1.55) = 45.0
// stdev4 = 223378541517576601.6, log(stdev4/1.55) = 57.0
// 
// Repetition rate
// M1 = 2.5699382
// M2 = 1.6199165
// M3 = 1.0448095
// M4 = 1.0249634
// total = 4.4582127
// 
// Security
// MSIS dimension: 7
// MSIS root hermite factor: 1.0042705
// MLWE dimension: 74
// MLWE root hermite factor: 1.0043564
// 
// Proof size
// ~ 77.1855468750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241, 1125899906824961]
// bit length of products: [49, 99, 149, 199, 249]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893, -134010426262513]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {1813UL, 18014398509481984UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {1812UL, 18014398509481984UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {10592219861509258290UL, 5021639489UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {14519481967609404953UL, 2510819744UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {3587354UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {1793677UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {8192UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {4096UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {2673109138833674UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {16703122918921151033UL, 10513503571854739674UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {2116213570330962431UL, 11435441538628748701UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {8359285712312153455UL, 826588900562575676UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {17218250918052787657UL, 460493985074998520UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {165098542858UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {14019525496019259228UL, 161229045UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {2951479051793528259UL, 2704974526189404UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {906UL, 9007199254740992UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {453UL, 4503599627370496UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 2, 1}};
static const unsigned int _param_n[2] = {32, 32};
static const limb_t _param_Bz3sqr_limbs[] = {16243760109450862123UL, 111012260217UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {3574056664281225625UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {39363UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {737868883424979190UL, 41943UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 2, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1};
static const polyring_t _param_ring = {{_param_q, 64, 119, 6, moduli_d64, 5, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 13, 0, 97 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 66, 124, 32, 11, 7, _param_Bsq, 1, 8, 5, 140, 1, 18, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 66, 124, 41, 2, 7, _param_Bsq, 1, 8, 5, 140, 1, 18, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 66, 124, 42, 1, 7, _param_Bsq, 1, 8, 5, 140, 1, 18, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 32, _param_n, 64, 2, 98, 2, 45, _param_scM3, _param_stdev3sq, 2, 57, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 79038UL }};

static const unsigned int param_Ps[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int param_Es0[32] = {32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {32};
static const unsigned int param_Em0[32] = {64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95};
static const unsigned int *param_Em[1] = { param_Em0, };
static const unsigned int param_Em_nrows[1] = {32};
static const unsigned int param_m_indices[1] = {2};

static const limb_t param_p_limbs[] = {18014398509481985UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {10949706387073277057UL, 7321325865855737UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 1}};
static const unsigned int param_s1_indices[2] = {0, 1};
static const lin_params_t param = {{ _param, 2048, param_p, param_pinv, 32, param_s1_indices, 2, param_m_indices, 1,  param_Ps, 32, param_Es, param_Es_nrows, param_Es, param_Es_nrows }};

