// auto-generated by lnp-quad-eval-codegen.sage from ../vdec/vdec_params_tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(42,51,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0)
// 
// Ring
// degree d = 64
// modulus q = 147573952589676413813, log(q) ~ 67.0
// factors q = q1
// 
// Compression
// D = 8
// gamma = 515068, log(gamma) ~ 18.974403
// m = (q-1)/gamma = 286513533338659, log(m) ~ 48.025597
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 38
// s2: m2 = 93
// 
// Size of secrets
// l2(s1) <= alpha = 135.7645
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 101580.8, log(stdev2/1.55) = 16.0
// 
// Repetition rate
// M1 = 3.5095422
// M2 = 4.1685048
// total = 14.629543
// 
// Security
// MSIS dimension: 11
// MSIS root hermite factor: 1.0043962
// MLWE dimension: 42
// MLWE root hermite factor: 1.004382
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t params1_q_limbs[] = {885UL, 8UL};
static const int_t params1_q = {{(limb_t *)params1_q_limbs, 2, 0}};
static const limb_t params1_qminus1_limbs[] = {884UL, 8UL};
static const int_t params1_qminus1 = {{(limb_t *)params1_qminus1_limbs, 2, 0}};
static const limb_t params1_m_limbs[] = {286513533338659UL, 0UL};
static const int_t params1_m = {{(limb_t *)params1_m_limbs, 2, 0}};
static const limb_t params1_mby2_limbs[] = {0};
static const int_t params1_mby2 = {{(limb_t *)params1_mby2_limbs, 1, 0}};
static const limb_t params1_gamma_limbs[] = {515068UL, 0UL};
static const int_t params1_gamma = {{(limb_t *)params1_gamma_limbs, 2, 0}};
static const limb_t params1_gammaby2_limbs[] = {257534UL, 0UL};
static const int_t params1_gammaby2 = {{(limb_t *)params1_gammaby2_limbs, 2, 0}};
static const limb_t params1_pow2D_limbs[] = {256UL, 0UL};
static const int_t params1_pow2D = {{(limb_t *)params1_pow2D_limbs, 2, 0}};
static const limb_t params1_pow2Dby2_limbs[] = {128UL, 0UL};
static const int_t params1_pow2Dby2 = {{(limb_t *)params1_pow2Dby2_limbs, 2, 0}};
static const limb_t params1_Bsq_limbs[] = {338252413746587UL, 0UL, 0UL, 0UL};
static const int_t params1_Bsq = {{(limb_t *)params1_Bsq_limbs, 4, 0}};
static const limb_t params1_scM1_limbs[] = {3162355462835707339UL, 9399394807438489735UL, 3UL};
static const int_t params1_scM1 = {{(limb_t *)params1_scM1_limbs, 3, 0}};
static const limb_t params1_scM2_limbs[] = {17325719994026335087UL, 3108364346459882899UL, 4UL};
static const int_t params1_scM2 = {{(limb_t *)params1_scM2_limbs, 3, 0}};
static const limb_t params1_stdev1sq_limbs[] = {41274635715UL, 0UL, 0UL, 0UL};
static const int_t params1_stdev1sq = {{(limb_t *)params1_stdev1sq_limbs, 4, 0}};
static const limb_t params1_stdev2sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t params1_stdev2sq = {{(limb_t *)params1_stdev2sq_limbs, 4, 0}};
static const limb_t params1_inv2_limbs[] = {442UL, 4UL};
static const int_t params1_inv2 = {{(limb_t *)params1_inv2_limbs, 2, 1}};
static const polyring_t params1_ring = {{params1_q, 64, 68, 6, moduli_d64, 3, params1_inv2}};
static const dcompress_params_t params1_dcomp = {{ params1_q, params1_qminus1, params1_m, params1_mby2, params1_gamma, params1_gammaby2, params1_pow2D, params1_pow2Dby2, 8, 1, 49 }};
static const abdlop_params_t params1_quad_eval = {{ params1_ring, params1_dcomp, 32, 93, 38, 2, 11, params1_Bsq, 1, 8, 5, 140, 1, 17, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const abdlop_params_t params1_quad_many = {{ params1_ring, params1_dcomp, 32, 93, 39, 1, 11, params1_Bsq, 1, 8, 5, 140, 1, 17, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const lnp_quad_eval_params_t params1 = {{ params1_quad_eval, params1_quad_many, 2}};

