// auto-generated by lnp-quad-eval-codegen.sage from ../vdec/vdec_params.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(40,19,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0)
// 
// Ring
// degree d = 64
// modulus q = 9223372036854776261, log(q) ~ 63.0
// factors q = q1
// 
// Compression
// D = 8
// gamma = 114860, log(gamma) ~ 16.809517
// m = (q-1)/gamma = 80300992833491, log(m) ~ 46.190483
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 5
// s2: m2 = 59
// 
// Size of secrets
// l2(s1) <= alpha = 1.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 1587.2, log(stdev1/1.55) = 10.0
// stdev2 = 101580.8, log(stdev2/1.55) = 16.0
// 
// Repetition rate
// M1 = 3.2656121
// M2 = 3.114691
// total = 10.376848
// 
// Security
// MSIS dimension: 11
// MSIS root hermite factor: 1.0043937
// MLWE dimension: 40
// MLWE root hermite factor: 1.0043312
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t params1_q_limbs[] = {9223372036854776261UL};
static const int_t params1_q = {{(limb_t *)params1_q_limbs, 1, 0}};
static const limb_t params1_qminus1_limbs[] = {9223372036854776260UL};
static const int_t params1_qminus1 = {{(limb_t *)params1_qminus1_limbs, 1, 0}};
static const limb_t params1_m_limbs[] = {80300992833491UL};
static const int_t params1_m = {{(limb_t *)params1_m_limbs, 1, 0}};
static const limb_t params1_mby2_limbs[] = {0};
static const int_t params1_mby2 = {{(limb_t *)params1_mby2_limbs, 1, 0}};
static const limb_t params1_gamma_limbs[] = {114860UL};
static const int_t params1_gamma = {{(limb_t *)params1_gamma_limbs, 1, 0}};
static const limb_t params1_gammaby2_limbs[] = {57430UL};
static const int_t params1_gammaby2 = {{(limb_t *)params1_gammaby2_limbs, 1, 0}};
static const limb_t params1_pow2D_limbs[] = {256UL};
static const int_t params1_pow2D = {{(limb_t *)params1_pow2D_limbs, 1, 0}};
static const limb_t params1_pow2Dby2_limbs[] = {128UL};
static const int_t params1_pow2Dby2 = {{(limb_t *)params1_pow2Dby2_limbs, 1, 0}};
static const limb_t params1_Bsq_limbs[] = {117220916596948UL, 0UL};
static const int_t params1_Bsq = {{(limb_t *)params1_Bsq_limbs, 2, 0}};
static const limb_t params1_scM1_limbs[] = {14472152395081010487UL, 4899677638543494430UL, 3UL};
static const int_t params1_scM1 = {{(limb_t *)params1_scM1_limbs, 3, 0}};
static const limb_t params1_scM2_limbs[] = {351663827259534233UL, 2115674991949461495UL, 3UL};
static const int_t params1_scM2 = {{(limb_t *)params1_scM2_limbs, 3, 0}};
static const limb_t params1_scM4_limbs[] = {17548352852960088280UL, 372648949419549295UL, 1UL};
static const int_t params1_scM4 = {{(limb_t *)params1_scM4_limbs, 3, 0}};
static const limb_t params1_stdev1sq_limbs[] = {2519204UL, 0UL};
static const int_t params1_stdev1sq = {{(limb_t *)params1_stdev1sq_limbs, 2, 0}};
static const limb_t params1_stdev2sq_limbs[] = {10318658929UL, 0UL};
static const int_t params1_stdev2sq = {{(limb_t *)params1_stdev2sq_limbs, 2, 0}};
static const limb_t params1_inv2_limbs[] = {4611686018427388130UL};
static const int_t params1_inv2 = {{(limb_t *)params1_inv2_limbs, 1, 1}};
static const limb_t params1_inv4_limbs[] = {2305843009213694065UL};
static const int_t params1_inv4 = {{(limb_t *)params1_inv4_limbs, 1, 1}};
static const polyring_t params1_ring = {{params1_q, 64, 64, 6, moduli_d64, 3, params1_inv2}};
static const dcompress_params_t params1_dcomp = {{ params1_q, params1_qminus1, params1_m, params1_mby2, params1_gamma, params1_gammaby2, params1_pow2D, params1_pow2Dby2, 8, 1, 47 }};
static const abdlop_params_t params1_quad_eval = {{ params1_ring, params1_dcomp, 32, 59, 5, 3, 11, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const abdlop_params_t params1_quad_many = {{ params1_ring, params1_dcomp, 32, 59, 7, 1, 11, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const lnp_quad_eval_params_t params1 = {{ params1_quad_eval, params1_quad_many, 4, params1_inv4, params1_scM4}};

